In [42]:
import pandas as pd
import numpy as np

In [71]:
data = pd.read_csv('books_cooks.csv')
data = data[data['genres']== 'Cookbooks']
data = data[0:250]

In [75]:
data1 = pd.read_csv('books_biography.csv')
data1 = data1[data1['genres']== 'Biography']
#data1 = data1[0:250]

In [77]:
data2 = pd.read_csv('books_biography1.csv')
data2 = data2[data2['genres']== 'Biography']

In [46]:
data3 = pd.read_csv('books_biography2.csv')
data3 = data3[data3['genres']== 'Biography']

In [78]:
data4 = pd.read_csv('books_biography3.csv')
data4 = data4[data4['genres']== 'Biography']

In [79]:
data5 = pd.read_csv('books_biography4.csv')
data5 = data5[data5['genres']== 'Biography']

In [80]:
data6 = pd.read_csv('books_biography5.csv')
data6 = data6[data6['genres']== 'Biography']

In [81]:
data7 = pd.read_csv('books_biography6.csv')
data7 = data7[data7['genres']== 'Biography']

In [82]:
data7['genres'].value_counts()

Biography    15
Name: genres, dtype: int64

In [84]:
data1 =  data1.append(data2)
data1

,name,author,link,text,picture,page number,rating,publications,genres
0,The Glass Castle,Jeannette Walls,https://www.goodreads.com/book/show/7445.The_G...,"A tender, moving tale of unconditional love in...",https://i.gr-assets.com/images/S/compressed.ph...,288 pages,4.28,\r\n Published\r\n January 1...,Biography
2,Angela's Ashes,Frank McCourt,https://www.goodreads.com/book/show/252577.Ang...,Imbued on every page with Frank McCourt's asto...,https://i.gr-assets.com/images/S/compressed.ph...,452 pages,4.12,\r\n Published\r\n October 3...,Biography
5,Tuesdays with Morrie,Mitch Albom,https://www.goodreads.com/book/show/6900.Tuesd...,"Maybe it was a grandparent, or a teacher or a ...",https://i.gr-assets.com/images/S/compressed.ph...,210 pages,4.12,\r\n Published\r\n 2000\r\n ...,Biography
7,Running with Scissors,Augusten Burroughs,https://www.goodreads.com/book/show/242006.Run...,Running with Scissors is the true story of a b...,https://i.gr-assets.com/images/S/compressed.ph...,304 pages,3.73,\r\n Published\r\n June 1st ...,Biography
9,"A Child Called ""It""",Dave Pelzer,https://www.goodreads.com/book/show/60748.A_Ch...,Also see: Alternate Cover Editions for this IS...,https://i.gr-assets.com/images/S/compressed.ph...,184 pages,4.11,\r\n Published\r\n September...,Biography
...,...,...,...,...,...,...,...,...,...
300,Parched,Heather King,https://www.goodreads.com/book/show/237287.Par...,One woman's journey to the bottom of the bottl...,https://i.gr-assets.com/images/S/compressed.ph...,276 pages,3.69,\r\n Published\r\n September...,Biography
308,Change Me into Zeus's Daughter: A Memoir,Barbara Robinette Moss,https://www.goodreads.com/book/show/181433.Cha...,A haunting and triumphant story of a difficult...,https://i.gr-assets.com/images/S/compressed.ph...,320 pages,4.03,\r\n Published\r\n August 7t...,Biography
321,Histoire de ma vie : édition définitive du man...,Giacomo Casanova,https://www.goodreads.com/book/show/18242273-h...,Cette nouvelle édition de l’Histoire de ma vie...,https://i.gr-assets.com/images/S/compressed.ph...,1573 pages,3.54,\r\n Published\r\n April 201...,Biography
322,Goat: A Memoir,Brad Land,https://www.goodreads.com/book/show/281221.Goat,Reeling from a terrifying assault that has lef...,https://i.gr-assets.com/images/S/compressed.ph...,224 pages,3.10,\r\n Published\r\n March 1st...,Biography
338,"Expecting Adam: A True Story of Birth, Rebirth...",Martha N. Beck,https://www.goodreads.com/book/show/349504.Exp...,"The ""slyly ironic, frequently hilarious""(Time)...",https://i.gr-assets.com/images/S/compressed.ph...,336 pages,3.83,\r\n Published\r\n August 1s...,Biography

In [53]:
data1 = data1.append(data3)

In [54]:
data1 = data1.append(data4)

In [55]:
data1 = data1.append(data5)

In [56]:
data1 = data1.append(data6)

In [57]:
data1 = data1.append(data7)
data1

,name,author,link,text,picture,page number,rating,publications,genres
0,The Glass Castle,Jeannette Walls,https://www.goodreads.com/book/show/7445.The_G...,"A tender, moving tale of unconditional love in...",https://i.gr-assets.com/images/S/compressed.ph...,288 pages,4.28,\r\n Published\r\n January 1...,Biography
2,Angela's Ashes,Frank McCourt,https://www.goodreads.com/book/show/252577.Ang...,Imbued on every page with Frank McCourt's asto...,https://i.gr-assets.com/images/S/compressed.ph...,452 pages,4.12,\r\n Published\r\n October 3...,Biography
5,Tuesdays with Morrie,Mitch Albom,https://www.goodreads.com/book/show/6900.Tuesd...,"Maybe it was a grandparent, or a teacher or a ...",https://i.gr-assets.com/images/S/compressed.ph...,210 pages,4.12,\r\n Published\r\n 2000\r\n ...,Biography
7,Running with Scissors,Augusten Burroughs,https://www.goodreads.com/book/show/242006.Run...,Running with Scissors is the true story of a b...,https://i.gr-assets.com/images/S/compressed.ph...,304 pages,3.73,\r\n Published\r\n June 1st ...,Biography
9,"A Child Called ""It""",Dave Pelzer,https://www.goodreads.com/book/show/60748.A_Ch...,Also see: Alternate Cover Editions for this IS...,https://i.gr-assets.com/images/S/compressed.ph...,184 pages,4.11,\r\n Published\r\n September...,Biography
...,...,...,...,...,...,...,...,...,...
68,Stories of My Life,Katherine Paterson,https://www.goodreads.com/book/show/20534704-s...,From her childhood in China to the moment she ...,https://i.gr-assets.com/images/S/compressed.ph...,320 pages,3.98,\r\n Published\r\n October 1...,Biography
87,Assata: An Autobiography,Assata Shakur,https://www.goodreads.com/book/show/100322.Assata,"On May 2, 1973, Black Panther Assata Shakur (a...",https://i.gr-assets.com/images/S/compressed.ph...,274 pages,4.57,\r\n Published\r\n November ...,Biography
95,Interesting Times: A Twentieth-Century Life,Eric J. Hobsbawm,https://www.goodreads.com/book/show/43087.Inte...,"Eric Hobsbawm es, en palabras de Orlando Figes...",https://i.gr-assets.com/images/S/compressed.ph...,448 pages,4.06,\r\n Published\r\n May 16th ...,Biography
102,Ray By Ray: A Daughter's Take on the Legend of...,Nicca Ray,https://www.goodreads.com/book/show/48752292-r...,Nicholas Ray was cinema. The legendary directo...,https://i.gr-assets.com/images/S/compressed.ph...,386 pages,4.24,\r\n Published\r\n April 28t...,Biography
109,"Sigh, Gone: A Misfit's Memoir of Great Books, ...",Phuc Tran,https://www.goodreads.com/book/show/45046838-s...,For anyone who has ever felt like they don't b...,https://i.gr-assets.com/images/S/compressed.ph...,320 pages,4.29,\r\n Published\r\n April 21s...,Biography

In [58]:
data1 = data1[0:250]

In [59]:
data1

,name,author,link,text,picture,page number,rating,publications,genres
0,The Glass Castle,Jeannette Walls,https://www.goodreads.com/book/show/7445.The_G...,"A tender, moving tale of unconditional love in...",https://i.gr-assets.com/images/S/compressed.ph...,288 pages,4.28,\r\n Published\r\n January 1...,Biography
2,Angela's Ashes,Frank McCourt,https://www.goodreads.com/book/show/252577.Ang...,Imbued on every page with Frank McCourt's asto...,https://i.gr-assets.com/images/S/compressed.ph...,452 pages,4.12,\r\n Published\r\n October 3...,Biography
5,Tuesdays with Morrie,Mitch Albom,https://www.goodreads.com/book/show/6900.Tuesd...,"Maybe it was a grandparent, or a teacher or a ...",https://i.gr-assets.com/images/S/compressed.ph...,210 pages,4.12,\r\n Published\r\n 2000\r\n ...,Biography
7,Running with Scissors,Augusten Burroughs,https://www.goodreads.com/book/show/242006.Run...,Running with Scissors is the true story of a b...,https://i.gr-assets.com/images/S/compressed.ph...,304 pages,3.73,\r\n Published\r\n June 1st ...,Biography
9,"A Child Called ""It""",Dave Pelzer,https://www.goodreads.com/book/show/60748.A_Ch...,Also see: Alternate Cover Editions for this IS...,https://i.gr-assets.com/images/S/compressed.ph...,184 pages,4.11,\r\n Published\r\n September...,Biography
...,...,...,...,...,...,...,...,...,...
91,"C. H. Spurgeon Autobiography: The Early Years,...",Charles Haddon Spurgeon,https://www.goodreads.com/book/show/436615.C_H...,"The story of Spurgeon's life, largely in his o...",https://i.gr-assets.com/images/S/compressed.ph...,562 pages,4.53,\r\n Published\r\n December ...,Biography
7,Sugar Ray,Dave Anderson,https://www.goodreads.com/book/show/1076540.Su...,Sugar Ray Robinson (1921–1989) was hailed as t...,https://i.gr-assets.com/images/S/compressed.ph...,380 pages,4.14,\r\n Published\r\n March 22n...,Biography
9,Confessions of a Tax Collector: One Man's Tour...,Rick Yancey,https://www.goodreads.com/book/show/196519.Con...,"Twelve years ago, Richard Yancey answered a bl...",https://i.gr-assets.com/images/S/compressed.ph...,400 pages,3.60,\r\n Published\r\n December ...,Biography
10,Welfare Brat,Mary Childers,https://www.goodreads.com/book/show/224228.Wel...,Mary Childers's intimate and frank memoir tell...,https://i.gr-assets.com/images/S/compressed.ph...,263 pages,3.69,\r\n Published\r\n May 1st 2...,Biography
15,"Welcome, Silence",Carol S. North,https://www.goodreads.com/book/show/590919.Wel...,This is the amazing true story of one woman's ...,https://i.gr-assets.com/images/S/compressed.ph...,324 pages,4.03,\r\n Published\r\n January 1...,Biography

In [60]:
data = data.append(data1)

In [61]:
data.to_csv("DATA.csv")

In [62]:
data8 = pd.read_csv("books_poetry.csv")
data8 = data8[data8['genres']== 'poetry']
data8 = data8[0:250]

In [63]:
datas = pd.read_csv("DATA.csv")

In [64]:
datas = datas.append(data8)

In [65]:
datas.to_csv("BOOKS3.csv")

In [66]:
dat = pd.read_csv("BOOKS3.csv")

In [67]:
dat = dat.drop(["Unnamed: 0","Unnamed: 0.1"],axis=1)

In [68]:
dat.to_csv("BOOKS3.csv")

In [69]:
dat = pd.read_csv("BOOKS3.csv")

In [70]:
dat

,Unnamed: 0,name,author,link,text,picture,page number,rating,publications,genres
0,0,The Joy of Cooking,Irma S. Rombauer,https://www.goodreads.com/book/show/327847.The...,"Since its original publication, Joy of Cooking...",https://i.gr-assets.com/images/S/compressed.ph...,1152 pages,4.09,\r\n Published\r\n November ...,Cookbooks
1,1,How to Cook Everything: Simple Recipes for Gre...,Mark Bittman,https://www.goodreads.com/book/show/603204.How...,\r\nGreat Food Made Simple\r\n Here's the brea...,https://i.gr-assets.com/images/S/compressed.ph...,960 pages,3.96,\r\n Published\r\n August 28...,Cookbooks
2,2,Better Homes and Gardens New Cook Book,Better Homes and Gardens,https://www.goodreads.com/book/show/411053.Bet...,"Features: Over 900 new recipes -- 1,200 in all...",https://i.gr-assets.com/images/S/compressed.ph...,576 pages,4.10,\r\n Published\r\n September...,Cookbooks
3,3,Betty Crocker's Cookbook,Betty Crocker,https://www.goodreads.com/book/show/1127996.Be...,The new and revised edition of Betty Crocker's...,https://i.gr-assets.com/images/S/compressed.ph...,575 pages,4.24,\r\n Published\r\n December ...,Cookbooks
4,4,The Moosewood Cookbook: Recipes from Moosewood...,Mollie Katzen,https://www.goodreads.com/book/show/603422.The...,Among the most influential cookbooks of our ti...,https://i.gr-assets.com/images/S/compressed.ph...,221 pages,3.85,\r\n Published\r\n October 1...,Cookbooks
...,...,...,...,...,...,...,...,...,...,...
495,495,"C. H. Spurgeon Autobiography: The Early Years,...",Charles Haddon Spurgeon,https://www.goodreads.com/book/show/436615.C_H...,"The story of Spurgeon's life, largely in his o...",https://i.gr-assets.com/images/S/compressed.ph...,562 pages,4.53,\r\n Published\r\n December ...,Biography
496,496,Sugar Ray,Dave Anderson,https://www.goodreads.com/book/show/1076540.Su...,Sugar Ray Robinson (1921–1989) was hailed as t...,https://i.gr-assets.com/images/S/compressed.ph...,380 pages,4.14,\r\n Published\r\n March 22n...,Biography
497,497,Confessions of a Tax Collector: One Man's Tour...,Rick Yancey,https://www.goodreads.com/book/show/196519.Con...,"Twelve years ago, Richard Yancey answered a bl...",https://i.gr-assets.com/images/S/compressed.ph...,400 pages,3.60,\r\n Published\r\n December ...,Biography
498,498,Welfare Brat,Mary Childers,https://www.goodreads.com/book/show/224228.Wel...,Mary Childers's intimate and frank memoir tell...,https://i.gr-assets.com/images/S/compressed.ph...,263 pages,3.69,\r\n Published\r\n May 1st 2...,Biography
499,499,"Welcome, Silence",Carol S. North,https://www.goodreads.com/book/show/590919.Wel...,This is the amazing true story of one woman's ...,https://i.gr-assets.com/images/S/compressed.ph...,324 pages,4.03,\r\n Published\r\n January 1...,Biography